theme: jekyll-theme-midnight
title: Amirreza Bahoush Resume
description: Frontend Developer
avatar: https://avatars.githubusercontent.com/u/69066265?s=400&u=7bc0347d34ec1a1075b61e15ab20be5d832288c2&v=4
